# ????????? ??????????? ? PostgreSQL
db.host=localhost
db.port=5433
db.name=prog_lab5
db.username=postgres
db.password=postgres

# ????????? ???? ??????????
db.pool.min=2
db.pool.max=10
db.pool.timeout=30000